### ISSUE TITLE
WASM (WebAssembly)

### ISSUE THREAD

**Issue by Meridiano** [macchrome/winchrome#103]
[regex101.com](https://regex101.com/) returns error about WebAssembly is being off.
Debug results: Worker=true, Promise=true, WASM=false.

chrome://flags/ tweaked (all set to enabled):
#enable-experimental-webassembly-features
#enable-experimental-webassembly-stack-switching
#enable-webassembly-baseline
#enable-webassembly-garbage-collection
#enable-webassembly-lazy-compilation
#enable-webassembly-relaxed-simd
#enable-webassembly-stringref
#enable-webassembly-tiering

No changes. 114.0.5735.134 of Google Chrome works, 114.0.5735.134 of this ungoogled-chromium not works.

UPD: Looks like `chrome://flags/#enable-webassembly` is just missing and cannot be enabled manually.

**Comment by macchrome** [comment]
Enable JavaScript Jit:  chrome://settings/content/javascript-jit

Make sure that --js-flags="--jitless" is not defined at the CLI

**Comment by Rusenche** [comment]
@macchrome 

Unfortunately this does not work on https://up-load.io/1bv6wr29l23y when using https://github.com/Wikidepia/hektCaptcha-extension/releases/tag/v0.3.0b3.

It always gives an error.... And because the error is so big that here github says: "**You can't comment at this time — your comment is too long (maximum is 65536 characters).**"

So I am attaching a text file.

[Aborted (no native wasm support detected).txt](https://github.com/macchrome/winchrome/files/12420253/Aborted.no.native.wasm.support.detected.txt)

![249503013-1ef0528e-79f5-4313-8d71-2680080c7b49](https://github.com/macchrome/winchrome/assets/18578128/f5dbeb50-fc6e-4670-af40-317cfb7f2689)

And this error is with enabled:
- JavaScript Jit;
- webgl.

For reference: https://github.com/Wikidepia/hektCaptcha-extension/issues/45#issuecomment-1614025471
