### ISSUE TITLE
crash opening site settings window in 116.0.5845.141

### ISSUE THREAD

**Issue by TeeTeeHaa** [macchrome/winchrome#110]
I have a reproducible hard crash when opening site settings in Marmaduke's Ungoogled Chromium.

I am reporting the isse here because I use the build of this repository. If this issue is more generic I can even reported in a more generic repository of Chromium. Please tell me which repository would be the best to report it.

**System**

Version 116.0.5845.141 (Official Build, ungoogled-chromium) (64-bit)
https://github.com/macchrome/winchrome/releases/download/v116.5845.141-M116.0.5845.141-r1160321-Win64/ungoogled-chromium-116.0.5845.141-1_Win64.7z

Edition Windows 10 Pro
Version 21H2
Installed on 05/07/2020
OS build 19044.3086
Experience Windows Feature Experience Pack 1000.19041.1000.0

**Steps to Reproduce**

1. Optionally delete folder `C:\Users\<username>\AppData\Local\Chromium\User Data` to proceed it with a fresh installation.
2. Open Chromium.
3. Open any website, for example https://www.chromium.org/chromium-projects/
4. Click on the lock icon left of the URL.
5. Click on "Site settings".
6. Observe the window opening, notice the empty drop down boxes, then observe crash (whole Chromium window just dissappears).

Log generated with `chrome.exe --enable-logging=stderr --v=1 > log.txt 2>&1` is attached. Its last line is `[8440:11048:0901/100812.305:ERROR:site_settings_helper.cc(524)] 67 does not have a readable name.`

[log.txt](https://github.com/macchrome/winchrome/files/12496000/log.txt)

**Comment by macchrome** [comment]
The crash has been noted, and can confirm that the same behaviour is noted in Cromite for Windows 116.0.5845.163 and is caused by the addition of:

chrome://settings/content/javascript-jit
chrome://settings/content/webgl
chrome://settings/content/webrtc

**Friday, 1 September 2023**

_Site settings address bar fix_


No Sync - WebRTC - Widevine - All Codecs - ThinLTO - Ungoogled

ungoogled-chromium-116.0.5845.141-2_Win64.7z (64-bit)
https://github.com/macchrome/winchrome/releases/download/v116.5845.141-M116.0.5845.141-r1160321-Win64/ungoogled-chromium-116.0.5845.141-2_Win64.7z
SHA1 CF7127F24C2E55EC7C7189943DAFF146AE7A81FF

==================

116.0.5845.141-2_ungoogled_mini_installer.exe (64-bit)
https://github.com/macchrome/winchrome/releases/download/v116.5845.141-M116.0.5845.141-r1160321-Win64/116.0.5845.141-2_ungoogled_mini_installer.exe
SHA1 375FA6BCDA421031C1BADD517938CB264261F97C

**Comment by Rexadev** [comment]
@macchrome How to manually install update for Portable "ungoogled-chromium-116.0.5845.141-2_Win64.7z" is not automatically updating though chrlauncher.

**Comment by TeeTeeHaa** [comment]
@macchrome I tried the build you linked above and I can confirm that it does not crash anymore. 👍

To both @macchrome and @uazo: Thank you for providing great open source software based on other open source software.
