### ISSUE TITLE
Impossible to play video from https://ok.ru/video 

### ISSUE THREAD

**Issue by trimechee** [macchrome/winchrome#118]
Hello, thank you so much for this new awesome version :) 💯 🥇 

It seems that we can"t play any more videos from this famous website , with other browsers lke google chrome, librewolf.... i can play this videos : 

https://ok.ru/video

https://ok.ru/video/6393462721114

**Comment by Rusenche** [comment]
> @trimechee
> Hello, thank you so much for this new awesome version :) 💯 🥇
> 
> It seems that we can"t play any more videos from this famous website , with other browsers lke google chrome, librewolf.... i can play this videos :
> 
> https://ok.ru/video
> 
> https://ok.ru/video/6393462721114

Currently my current version is Ungoogled Chromium v.11**7**.0.5938.150 x64. I tested this clip that you indicate: https://ok.ru/video/6393462721114 and there is no problem.

You intrigued me that there is a problem and I decided to test the current uploaded so far Ungoogled Chromium v.11**8**.0.5993.71 x64 trying to see this clip from your opinion.

I confirm this issue. And it won't even let me copy the error, so I'm attaching a picture.

![STATUS_BREAKPOINT](https://github.com/macchrome/winchrome/assets/18578128/d6dd4a6f-be72-45d9-a5c6-d8730c5edcdc)

**Comment by trimechee** [comment]
@Rusenche Thank you so much for testing :) 👍 at the beginning I suspected ublock origin lite, or because I deactivated webassembly and webgl and webrtc...so I reset the default values and I authorized third-party cookies but still the same result, impossible to see the videos....maybe this site is blocked according to the user agent....on chrome with ublock origin activated and dns cira, it works without problem, the same for librewolf browser, video works

**Comment by Rusenche** [comment]
@trimechee, the site is not blocked because of the user agent. Already in my previous post I tested (for myself but didn't post) https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/tag/118.0.5993.70-1.1 and it worked there but I didn't feel like it wanted me to post another url to another repository here, but test from there just ungoogled-chromium_118.0.5993.70-1.1_windows_x64.zip and you'll see that the clip and the site render without any problems.

When I tested @macchrome's current Ungoogled Chromium v.11**8**.0.5993.71 x64 uploaded so far - it was by unzipping the files and running Chromium (everything with default settings only), but it's obvious that there is a problem, and it's possible that there is problems to other sites as well.

**Comment by trimechee** [comment]
Very interesting informations ! Thank you for helping  investigating this important problem :) 👍 💯

**Comment by macchrome** [comment]
The problem is caused by script at st.mycdn.me.

Someone will have to inspect the script: because I'm not going to make a concerted effort to fix it.

**Comment by trimechee** [comment]
Thanks for the explanation :) so who made this script please ? the problem is in the source code of Ungoogled chromium and we must open an issue in the github page of ungoogled chromium to fix this problem ?

**Comment by Rusenche** [comment]
@macchrome, your version 11**7** opens the site without problem with the same `st.mycdn.me` script you mentioned (you describe it as problematic). But this is not the case with your version 11**8** of your repository.

(How this script `st.mycdn.me` doesn't cause problem on version 11**7** from your repository but causes problem on version 11**8** also from your repository but doesn't cause problem on version 11**8** from the other ungoogled chromium project/repository...)

I assume it's due to the new version 11**8** of this repository, because as I wrote - this problem with the site mentioned in the first comment works without a problem with the other ungoogled chromium project version 11**8**. It's lucky that someone else didn't mention other sites.

**Comment by trimechee** [comment]
Mr @macchrome , i didn't see any more mention of uazo ad blocker in the descrption of the new relaeses of yout browser, have you abandoned the project to include this ad blocker in the web browser ?

**Comment by trimechee** [comment]
@Rusenche , thank you for this insight ! 

 what I don't understand is that the browser is based on ungoogled chromiumn so if there is no problem in ungoogled chromium, then logically there should be no problem with the browser of Mr Marmaduke....

we hope this problem will not affect other sites, I like using this web browser because it gives us the rare option to disable webassembly and webgl which can represent a big security risk....

We also hope that Google Safe Browsing protection will be integrated and optional in Mr Marmaduke's browser because it helps protect users from the installation of malicious extensions for example....

**Comment by macchrome** [comment]
@trimechee

Issue has been solved.

https://github.com/macchrome/winchrome/releases/tag/v118.5993.106-M118.0.5993.106-r1192594-Win64

Safe Browsing protection will never be integrated into one of my builds.

**Comment by Rusenche** [comment]
I confirm that the issue is resolved with `Ungoogled Chromium v.118.0.5993.106-1-r1192594`.

Thanks for the quick fix too, @macchrome.

**Comment by trimechee** [comment]
@macchrome Ohh that's wonderful ! Thanks a lot ! 🥇 💯

**Comment by Jadovran** [comment]
Problem returned in https://github.com/macchrome/winchrome/releases/download/v121.6167.140-M121.0.6167.140-r1233107-Win64/ungoogled-chromium-121.0.6167.140-1_Win64.7z can anyone help me?
