### ISSUE TITLE
Vital need of information

### ISSUE THREAD

**Issue by trimechee** [macchrome/winchrome#120]
Hello, I like using Mr Marmaduke's web browser because I can disable webassembly which can have security risks... but I just discovered this discussion which spreads doubt in my heart and my mind and soul because I thought I was blocking webassembly but after reading this discussion, 

chrome://settings/content/javascript-jit: Rephrase, acts Weird : 
https://github.com/macchrome/winchrome/issues/114

so I don't know any more if webassembly is enabled by default or not because it seems that the option in: chrome://settings/content/javascript-jit

applies individually and there is no blocking of wasm by default, does the web browser of Mr Marmaduke authorize webassembly by default and how can we block the webassembly by default please ?

**Comment by macchrome** [comment]
Figure it out for yourself with a site such as:  https://regex101.com/

**Comment by trimechee** [comment]
Thank you Mr @macchrome /

So Mr @Rusenche, what do you think please ? I am not technically competent, if we choose to block JIT in speciefic site, that means the browser will block wasm in all the websites by default ?

**Comment by Rusenche** [comment]
@trimechee and @macchrome

I was left with a problem that has not yet been solved, I have mentioned it:
- https://github.com/Wikidepia/hektCaptcha-extension/issues/45#issuecomment-1611453981
- https://github.com/macchrome/winchrome/issues/103#issuecomment-1690061795

According to the developer of the extension - @Wikidepia: `Your browser doesn't seem to support web assembly, I dont know why but my ungoogled chromium works fine. wasm is needed for onnx which is essential to this extension. no wasm no hekt. Sorry`.

@Wikidepia is using Ungoogled Chromium from the other repository and the `hektCaptcha-extension` works for it.

So far there is no solution and it is impossible to use the `hektCaptcha-extension` because `Ungoogled Chromium v.118.0.5993.118 x64` (from this repository) does not work with the extension. Unfortunately.

**Comment by trimechee** [comment]
@Rusenche Thank you for this interesting information :)

I was happy then disappointed at the same time: I use this streaming site where almost every video has captcha and it's annoying and tiring especially when you watch anime that have 700 episodes, then recently chromium has added this option to remove the captcha:

chrome://settings/content/autoVerify


but despite that, sometimes I have captchas so we will have to use addon extensions to delete captcha.....

We hope this problem will be resolved and we will no longer see captchas....
