### ISSUE TITLE
There is a problem with the new version Chromium v.119.0.6045.110-r1204232 - ungoogled and the "Session buddy" extension

### ISSUE THREAD

**Issue by Rusenche** [macchrome/winchrome#122]
There is a problem with the new version `Chromium v.119.0.6045.110-r1204232 - ungoogled` and the `Session buddy` extension.

I specifically tested with other chromium above 119 chromium version:
- https://github.com/Hibbiki/chromium-win64/releases/tag/v119.0.6045.106-r1204232;
- https://github.com/justclueless/chromium-win64/releases/tag/v121.0.6100.0-r0-AVX2.

`Session buddy` _extension_ (https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko/) is broken and doesn't work only on new version `Chromium v.119.0.6045.110-r1204232 - ungoogled` - https://github.com/macchrome/winchrome/releases/tag/v119.6045.110-M119.0.6045.110-r1204232-Win64.

I am attaching a photo to visually visualize the broken extension, which does not function at all and in no way. I tested the extension even with several previous versions, but it only breaks on `Chromium version v.119.0.6045.110-r1204232 - ungoogled`.

![error](https://github.com/macchrome/winchrome/assets/18578128/492fa785-cd68-4382-877c-1310bde4e24f)

Tested with a completely new profile.

Please @macchrome look into what is causing the problem.

Please @trimechee also test to confirm or disprove the issue.

**Comment by trimechee** [comment]
@Rusenche Sadly, it seems this extension has a bug to save open tabs with the last version v119.0.6045.110-r1204232  :( we hope ther will be fix soon with the future version !

**Comment by Rusenche** [comment]
@trimechee, thanks for the confirmation.

The bug is not in the extension because with previous versions of the extension - it still doesn't work on version `119.0.6045.110-r1204232` from this repository. But it works perfectly for me with v.`118.0.5993.118-r1192594` - https://github.com/macchrome/winchrome/releases/tag/v118.5993.118-M118.0.5993.118-r1192594-Win64.

Just in case, I checked the same extension but on @uazo's version - v.119.0.6045.106-9344cc41d5d85463ee12bc449c72ad335f7545fe from here: https://github.com/uazo/cromite/releases/tag/v119.0.6045.106-9344cc41d5d85463ee12bc449c72ad335f7545fe - but also at it extension does not work.

Something is broken in the new version 119 because on both @uazo and @macchrome the extension doesn't work.

This is because @Hibbiki's version 119 and @RobRich999's version v.`120.0.6096.0-r1216665-win64-avx2` **the extension also works flawlessly**.



**Supplement:**

I just tested the `ungoogled-chromium_119.0.6045.105-1.1_windows_x64.zip` posted 2 hours ago -
https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/tag/119.0.6045.105-1.1 and extension `Session buddy` also works flawlessly.

**Comment by trimechee** [comment]
@Rusenche Yes the version where te extension works is 119.0.6045.105-1.1 of unggoled chromium, la version du navigateur est en avance sur celle de ungoogled chromium, perhaps to avoid possible bugs, it is better that the browser has the same official version as ungoogled chromium....

**Comment by macchrome** [comment]
The only extensions that I use are nuTensor/uMatrix and uBlock Origin.

Session buddy is a low priority extension: use a browser that it's compatible with.

**Comment by g-k-m** [comment]
> There is a problem with the new version `Chromium v.119.0.6045.110-r1204232 - ungoogled` and the `Session buddy` extension.
> 
> I specifically tested with other chromium above 119 chromium version:
> 
> * https://github.com/Hibbiki/chromium-win64/releases/tag/v119.0.6045.106-r1204232;
> * https://github.com/justclueless/chromium-win64/releases/tag/v121.0.6100.0-r0-AVX2.
> 
> `Session buddy` _extension_ (https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko/) is broken and doesn't work only on new version `Chromium v.119.0.6045.110-r1204232 - ungoogled` - https://github.com/macchrome/winchrome/releases/tag/v119.6045.110-M119.0.6045.110-r1204232-Win64.
> 
> I am attaching a photo to visually visualize the broken extension, which does not function at all and in no way. I tested the extension even with several previous versions, but it only breaks on `Chromium version v.119.0.6045.110-r1204232 - ungoogled`.
> 
> ![error](https://user-images.githubusercontent.com/18578128/280485460-492fa785-cd68-4382-877c-1310bde4e24f.png)
> 
> Tested with a completely new profile.
> 
> Please @macchrome look into what is causing the problem.
> 
> Please @trimechee also test to confirm or disprove the issue.

Use https://tabler.one it's like 1000000 times better than Session Buddy

**Comment by Rusenche** [comment]
> @macchrome Session buddy is a low priority extension: use a browser that it's compatible with.

If the topic is closed, then maybe a solution to the problem has been found. But it's not like that...

> @g-k-m: Use https://tabler.one it's like 1000000 times better than Session Buddy

Something else is important here. What will you advise when the extension you suggested also stops working in `Chromium v.119.0.6045.110-r1204232 - ungoogled` or in a later version due to the browser and not some version of the extension?!

`Session buddy` is an excellent extension.

Due to neglecting the issue which is listed as `low priority`, I revert to `Ungoogled Chromium v.118.0.5993.118 x64`.

**Comment by macchrome** [comment]
It's obvious that the problem with your semi-precious  _Session buddy_ is due to the introduction of javascript-jit/webgl/webrtc. It's a low priority because the source of the problem is at least with the associated code, or with Session buddy.

**Comment by Rusenche** [comment]
Me as a user who can't build versions of Chromium - in this case what can I do?! Because it looks like it will be "frozen" on version 118 for a long time.

With "javascript-jit/webgl/webrtc" - nothing I can do from my side as a big fan and user of `Ungoogled Chromium` because they are implemented in the browser and I can't turn them off for extension... This browser is my favorite for years, the extension is also one of my favorites. Sad thing is that I can't migrate to any new browser version...

**Comment by trimechee** [comment]
@g-k-m Thank you for your interesting informations :) i have changed many hidden flags in the browser because I like to experiment and deactivate unnecessary functions to speed up the browser, so I fear that even with a new profile, my attempt to test this extension would not be very relevant... I had to do a new clean installation with the default values for that the test is really relevant... Mr macchrome says the problem is in javascript-jit/webgl/webrtc.....

**Comment by hansifer** [comment]
does setting `chrome://flags/#web-sql-access` to Enabled fix it?

**Comment by macchrome** [comment]
@hansifer

Well done mate. I appreciate constructive suggestions:  can report that Session Buddy 3.6.5 works correctly. I will check the chromium source to see if @uazo set this value to disabled by default.

trimechee and Rusenche, I've no time time for people who continuously moan, have nothing constructive to say and think that the world owes them a living.

**Comment by hansifer** [comment]
To add some more detail, this is of course a stopgap.

While the flag should be good through roughly March 2024, Session Buddy v4 will be released well before that and will no longer have a WebSQL dependency.

**Comment by trimechee** [comment]
@macchrome you are very rude and ungrateful and pretnetious, you are liar falsifier , shame on you, I have always spoken to you politely by calling you Mr, but you absolutely do not deserve that I respect you because you are rude and ungrateful, your browser does not implement Google protection safe browsing and the default protection against the installation of malicious programs, I don't even see the commits that you make so your browser is not even open source, and I spoke in this thread out of politeness for Mr Rusenche who asked for my help, really it is a great danger and error your navigation which uses the ideas of others, we do not know your identity, your real name and first name and your identity and where you reside, you can implement spy logic, malware, viruses, save your life and your data and uninstall this suspicious browser, use Thorium or the official version of ungoogled chromium, by the way it's illegal for you to activate the H264 codec in your shady browser, I can call the police and denounce you and the fbi put you in prison and you would be fined, so stay good anonymous marmaduke, you are an outlaw, you are anonymous, we cannot trust you and put our passwords in a browser an anonymous person who doesn't even make commits and who doesn't have a bio, websites, social networks.....even the official moderator of ungoogled chromium warned us against your browser and that it's risky to use your browser and marmaduke, you were cited in the discussion and you did not even have the honor and dignity to defend your browser when the moderator of ungoogled chromium said it is not recommended to use your browser , shame n you, even this vain anonymous marmaduke does not defend his browser against accusations, so you are not trustworthy


@PF4Public  advised us
"We do not provide support for binaries obtained outside of ungoogled-software GitHub organization and I would not recommend downloading and executing them. "

and the unworthy @ didn't even retaliate to defend his browser, you have no honor or dingity lol

https://github.com/ungoogled-software/ungoogled-chromium/issues/2567

@Rusenche please don't use this dagerous browser , there is the official binaries of ungoogled chromium, thorium.... the reason to use this dangerous anonymous brower is H264 codec but hardaware gpu nowadays support open source codec AV1, we don't need H264, and even if we need it, we can use edge browser, brave browser, arc browser....please save your security and no longer use this suspicious browser and do an antivirus scan and change your passwords.....

Mr @g-k-m, also i recommand you not to use this dangerous browser please

**Comment by trimechee** [comment]
@hansifer you are not anonymous, we see your photo and we know your first and last name, but the anonymous @, we know nothing about him, it is very suspicious to use a browser from an unknown anonymous person, please uninstall and no longer use this dangerous browser of this winmachin, and do an antivirus scan or new reinstallation of your os please

**Comment by trimechee** [comment]
@woolyss this marmaduke browser is suspicious and shady, because this marmaduke is anonymous and we know nothing about him, why he refuses to reveal his personal information like his photo and his real name and first name as a guarantee of trust and like other developers ? It is better to no longer put the dangerous browser link on your site:

https://chromium.woolyss.com/

and put instead the official link of the ungoogled chromium binaries, in addition on the browser of this marmaduke, there were bugs like in the ok.ru site, it uses not stable versions, and now there is a bug with this extension....its browser which uses other people's ideas is a nightmare and should be avoided

https://github.com/ungoogled-software/ungoogled-chromium-windows

**Comment by trimechee** [comment]
Mr @woolyss  , you are free but I think it is very dangerous to put second position in your website this browser of this anonymous marmaduke who by hatred of google deactivates the internal protection of chromium and google safe browsing which exposes users to malware viruses, at least he leaves the choice to activate or not google safe browsing....in addition his browser has bugs which do not exist in other browsers and he is even reluctant to correct them, this lazy marmaduke me said when I told him about this critical and shameful bug in the famous site ok.ru; marmaduke replied:

"The problem is caused by script at st.mycdn.me.

Someone will have to inspect the script: because I'm not going to make a concerted effort to fix it."


https://github.com/macchrome/winchrome/issues/118


it is better to put Thorium in second position or the offcial binaries of ungoogled chromium which is a tested and trusted browser and controlled by a whole team of trusted developers

**Comment by Rusenche** [comment]
> @macchrome:
> @hansifer
> 
> Well done mate. I appreciate constructive suggestions: can report that Session Buddy 3.6.5 works correctly. I will check the chromium source to see if @uazo set this value to disabled by default.
> 
> trimechee and Rusenche, I've no time time for people who continuously moan, have nothing constructive to say and think that the world owes them a living.


First: My personal thanks to @hansifer, to whom I had personally described the problem by e-mail and sent him an address to this topic! Thanks to @hansifer for immediately replying to me with several letters on e-mail and personally there he also wrote the solution to the problem, which solution he shared here with us.

@trimechee, Thorium has some imperfections, I've written threads and no solutions have been proposed yet, it's missing one basic functionality that doesn't work in Thorium, but works in Ungoogled chromium. @trimechee I agree with you about @macchrome. Yes, @macchrome is toxically arrogant, even though he knows it. He's unlikely to surprise anyone with his approach to pushing people away. I'll even take the liberty of replicating @macchrome - you think the users owe you?! It is constructive when you share a problem, describe the problem, present the problem with settled facts, with performed tests, and in the end we receive from you - a useless comment and instant locking of the topic and sending it to the "trash". This is a fact.

> @macchrome
> I will check the chromium source to see if @uazo set this value to disabled by default.

And why would you do it when you wrote that it is low priority?! Better not do it and feel like everyone owes you. Your attitude is offensive. And last but not least, @macchrome, github is not an environment for professionals only, so you should expect only professional programmers to join here, it is also a place for users who do not have this professional competence, but how would you know if you have the misconception that everyone owes you…

Once again, I publicly thank @hansifer for responding to my e-mail to him and looking into the issue, responding adequately and offering a working solution, joining the thread here, something we can't say about @macchrome at all.

@hansifer you have my respect, thank you very much for being a responsive and helpful person! You are a man of high morals!

**Comment by macchrome** [comment]
@Rusenche

> @macchrome
> I will check the chromium source to see if @uazo set this value to disabled by default.
> 
> And why would you do it when you wrote that it is low priority?! Better not do it and feel like everyone owes you. Your attitude is offensive.

Oh really!  Your ignorance I comprehend; but not your presumption.
