### ISSUE TITLE
Flag 'Overlay Scrollbars' stopped working with 119

### ISSUE THREAD

**Issue by achtchaern** [macchrome/winchrome#123]
The flag Overlay Scrollbars (chrome://flags/#overlay-scrollbars) stopped working. Last WinChrome version with the flag working was v118.0.5993.118. The Issue persists after deleting the profile under %LocalAppData%. 

With the [official Ungoogled Chromium builds for Windows](https://github.com/ungoogled-software/ungoogled-chromium-windows), the flag still works. They're on build 119.0.6045.105 though (as opposed to WinChrome v119.0.6045.110).

**Comment by macchrome** [comment]
I've disabled the chrome lab experiments  [IsChromeLabsEnabled() evaluates to false].

**Comment by achtchaern** [comment]
Thanks for your answer. Could you elaborate a bit about the connection between said lab experiments and the overlay scrollbars? The scrollbar flag has been around for years. Is there a way to re-enable the overlay scrollbars or do I have to stay on 118?

**Comment by macchrome** [comment]
The only substanive change that has been made to the standard ungoogled code and to uazo's code has been in:

https://source.chromium.org/chromium/chromium/src/+/refs/tags/119.0.6045.110:chrome/browser/ui/toolbar/chrome_labs_utils.cc;l=142


bool IsChromeLabsEnabled() {

  return false;
}

If the aberrant behaviour is due to the amended code, then I will not fix it: ungoogled under macOS was making repeated attempts to access the net, I wiresharked the connection and concluded that the removed code was responsible.

**Comment by achtchaern** [comment]
Hey, thanks for clarifying! How can we find out if it's your change or not? I'm not savy enough to compile on my own. The flag works in:

- Latest main UG build: 119.0.6045.105 (as mentioned)
- Official Chromium build: 121.xyz

Unfortunately, I can't find an official Chromium build with your exact version (.110). I know it's not the same, but in the UG .105 build, the overlay scrollbars feature remains functional even after disabling the "Enable Chrome Labs" flag. The flag 'Overlay scrollbars' has existed for about 10 years. 

Hopefully, the issue will be gone with your next update.

**Comment by achtchaern** [comment]
@macchrome 
Unfortunately, the overlay scrollbars still don't work in your 120 build.

**Comment by achtchaern** [comment]
@macchrome 
With your 120.0.6099.121 build, the overlay scrollbars are working again! Did you change the IsChromeLabsEnabled method back to default?
