### ISSUE TITLE
This version breaks video playing at Discovery+, previous version no problem.

### ISSUE THREAD

**Issue by Aftergit** [macchrome/winchrome#136]
This version breaks video playing at Discovery+, previous version no problem.

**Comment by macchrome** [comment]
State the actual version that you're using!

**Comment by Aftergit** [comment]
the latest Version 122.0.6261.126

**Comment by macchrome** [comment]
https://github.com/macchrome/winchrome/releases/tag/v122.6261.126-M122.0.6261.126-r1250580-Win64

Which revision?

**Comment by Aftergit** [comment]
Chromium v122.0.6261.126-r1250580

**Comment by macchrome** [comment]
Stop being obtuse!

**Comment by ltguillaume** [comment]
To be honest @macchrome, the way you release several iterations of the same build using `-1`, `-2` etc. is rather problematic imho:

1. People who subscribe to release notifications here on GitHub won't be notified at all
1. People (or programs) using the GitHub API won't see the change
1. The mini installer isn't updated
1. It's not very clear to know what's going on. I have had to have someone else point out to me that sometimes updated versions are released like that.

I would like to suggest that new iterations get a separate release, so that everyone gets notified and issues like this very one aren't opened.

**Comment by macchrome** [comment]
I understand what you're saying; but I will not tolerate  buffoonery.

Incremental releases (with a negligible build time) are for individuals who frequent GitHub and not for casual users.

**Comment by ltguillaume** [comment]
I honestly don't think @Aftergit had any idea what you meant when you asked "Which revision?" here, simply because it isn't as clear as you think it is that they had to look at which file they downloaded.

That being said, if you think that these incremental releases are only meant for those that happen know that you release incremental builds like this and not for people who happen to open an issue like this one, that is obviously your prerogative. Then I expect this sort of "buffoonery" will keep coming, though.
