### ISSUE TITLE
add explanation in readme and signed the builds

### ISSUE THREAD

**Issue by KonoromiHimaries** [macchrome/winchrome#16]
https://github.com/privacytoolsIO/privacytools.io/issues/1384

**Comment by woolyss** [comment]
Hello @KonoromiHimaries,

**_readme_** 
Note these builds are made by a developer, freely, without support, **in its spare time**. There is absolutely no business, no revenue.
You can find release info with each release (like in [this example](https://github.com/macchrome/winchrome/releases/tag/v78.0.3904.70-r693954-Win64)).

_**signed**_
Chromium is not signed because is open source and not "owned" per se by any one particular developer or organization.  Moreover, a certificate is not free for developers ([Example](http://www.freesmug.org/forum/t-8093500/chromium-osx-70-0-3538-67-available), [Apple Developer Program](https://developer.apple.com/support/purchase-activation/)).
