### ISSUE TITLE
After the last chromium ungoogled update. Extensions did not install from .crx

### ISSUE THREAD

**Issue by 5856751** [macchrome/winchrome#21]
After the last chromium ungoogled update. Extensions did not install and work. Installation does not work through .crx. But load unpacked works.

Version 78.0.3904.87 (Official Build) (64-bit)

**Comment by mooglestiltzkin** [comment]
You are correct. I also experienced the same issue since this latest 87 build.

The temporary fix is this for updating your extensions
https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/

I had to remove the extensions first, then do this to reinstall them. and import back the extensions settings (make sure to export settings first).

I hope this change isn't permanent, because it's a hell a lot inconvenient compared to click install extensions that we could do before.
