### ISSUE TITLE
After update to 103.0.5060.134-r1002911 almost every extension crashes

### ISSUE THREAD

**Issue by uDEV2019** [macchrome/winchrome#83]
After updating to the new version, almost every extension crashes at start of chromium.

Browser Tabs are not working and chrome://extensions/ isn't reachable anymore.

![image](https://user-images.githubusercontent.com/51911097/180032558-d501e56e-36ee-4371-b838-02b1316bf5e6.png)

**Comment by Crossbow-Killer** [comment]
Same.

**Comment by Lyceris-chan** [comment]
not sure why this issue got closed, I'm also running into this issue and the only way to get chrome working without wiping my data (which I haven't tried yet) has been to run the 114 build in win 8 compatibility mode

**Comment by uDEV2019** [comment]
> not sure why this issue got closed, I'm also running into this issue and the only way to get chrome working without wiping my data (which I haven't tried yet) has been to run the 114 build in win 8 compatibility mode

Not completely sure, but download for 134 got removed. I think thats, why this issue got closed.
https://chromium.woolyss.com/ gone back to 114

With 114 no problems for me under Win10 21H2.

**Comment by Lyceris-chan** [comment]
@uDEV2019 for some reason it only works in windows 8 compat mode here on W11 22H2

**Comment by spdfnet** [comment]
This update also messed up something in the profile folder.
Older versions have issues now, unable to open some of the internal pages like settings.

**Comment by HairyMilkshakes** [comment]
This update also bricked my Chromium installation. Please advise on a fix or resolution. @macchrome

**Comment by spdfnet** [comment]
> This update also bricked my Chromium installation. Please advise on a fix or resolution. @macchrome


I was able to keep my 'broken' profile by using the _nosync_ version from here:
https://github.com/Hibbiki/chromium-win64/releases/tag/v103.0.5060.134-r1002911

**Comment by HairyMilkshakes** [comment]
> > This update also bricked my Chromium installation. Please advise on a fix or resolution. @macchrome
> 
> I was able to keep my 'broken' profile by using the _nosync_ version from here: https://github.com/Hibbiki/chromium-win64/releases/tag/v103.0.5060.134-r1002911

Thanks for this - not very good on the dev part to not do any QA before releasing this... hope we hear an official response on what's going on.

**Comment by macchrome** [comment]
Launch chrome.exe or the portable launcher with Windows 8 compatibiliy mode.

The "issue" is related to sand-boxing: probably related to the fact that this pulled build incorporates a component build of ffmpeg, and that a tip of the tree compiler was used.

**Comment by uDEV2019** [comment]
@macchrome So, the problem has nothing to do with your provided package, am i right?
is there a timeline when you re-release 134?

**Comment by macchrome** [comment]
The problem is due to the compiler that has been used and/or the component build of ffmpeg. A successful build of Chromium is dependent on using the designated/default compiler.

The default compiler was not capable of producing an experimental polly optimised build; so, I built one that was capable, which I used to create a conventional build of ungoogled 103.0.5060.134.

Why the Chromium authors insist on using functionally useless builds of clang/llvm I do not know.

https://github.com/macchrome/winchrome/releases/download/v103.0.5060.134-r1002911-Win64/ungoogled-chromium-103.0.5060.134-1_Win64.7z

Run the launcher or chrome.exe in windows compatibility mode.

Subsequent builds of ungoogled will be compiled with the default compiler.

(Problem due to ffmpeg component build and sandboxing)
